### PR TITLE
darg-drop on chessboard added

### PR DESCRIPTION
**Pull request by sourabh32**
# Chessboard with Drag and Drop Functionality

Closes[#149](https://github.com/code100x/chess/issues/149)

In this update,  added drag and drop functionality to the existing chessboard component.

## Changes Made

- Added drag and drop functionality to the chessboard.
- Integrated drag and drop logic with the existing chess game logic.
- shows legal moves on drag start.

### CODE REVIEW

**Comment by ssk090** [comment]
Hey @sourabh32 , please attach some screenshots or video for reference for this PR

Thanks

**Comment by sourabh32** [comment]
@ssk090 

https://github.com/code100x/chess/assets/114211264/82160893-6442-4001-bdf4-17858aff2e6a

chess

**Comment by ssk090** [comment]
Hey @sourabh32 , the current board looks like this:
image

please check onces if you have the latest pull

Thanks

**Comment by Sama-004** [comment]
> @ssk090
> WhatsApp.Video.2024-04-21.at.2.52.30.PM.1.mp4
> chess

video is corrupt for me @ssk090 is it same for you?

**Comment by sourabh32** [comment]
idk

**Comment by sourabh32** [comment]
@ssk090  idk 
fork

**Comment by sourabh32** [comment]
sorry @ssk090  i know what went wrong

**Comment by amanShouts** [comment]
Hi, is the drag and drop functionality still open to work or its closed ? im confused

**Comment by ssk090** [comment]
@amanShouts https://github.com/code100x/chess/issues/149

**Pull request closed without merging**
