### PR TITLE
Added a `chess Bot`

### LINKED ISSUE #51: Add a bot that can play against a user

### PR DESCRIPTION
**Pull request by vishalmishraa**
closes #51 

Added a bot that play against user .

## VIDEO :

https://github.com/code100x/chess/assets/64027486/a0e37dff-da2e-47f9-94a4-f3686c2de499

## IMAGE : 
Screenshot 2024-04-24 at 5 47 39 PM

### CODE REVIEW

**Comment by vishalmishraa** [comment]
hey @hkirat  ,  Structured the file in more better way , all the conflicts are now resolved (for now) .
 Now it is ready to review.

**Comment by vishalmishraa** [comment]
> Same board colors and pieces being rendered in the play online and play with bot? If not , i think that would be ideal

yup , i changed it to default , same for both online and bot . 
https://github.com/code100x/chess/assets/64027486/ed40e3bf-2dab-4eeb-a9f3-c5224ba7cd27

**Comment by vishalmishraa** [comment]
hey @hkirat , i beautified the chess Bot UI too , and now it is same as play online mode with better options name like `famous chess players`, bots. if possible please review it .

**Comment by hkirat** [comment]
This is great
I see you've used chessboardjsx
We need to be consistent. Either need to use the library in both the type of games or remove it from both of them

**Comment by hkirat** [comment]
Happy to merge this as is but then we'll have to update the non bot rooms to use the same components

**Comment by vishalmishraa** [comment]
> Happy to merge this as is but then we'll have to update the non bot rooms to use the same components

i also wanted to used the non room chessBoard component , but that one required socket , but here i'm not using any socket connection . so i used chessboardjsx library.

**Comment by vishalmishraa** [comment]
> Happy to merge this as is but then we'll have to update the non bot rooms to use the same components

should i make a new component or , we can go with chessboardjsx for bot only?

**Comment by nimit9** [comment]
@hkirat hey I think we should use the chessboardjsx library. I think it can be easily integrated with chess.js as well.
Using just chess.js might cause problems in the future when adding more and more things


I can work on integrating chessboardjsx with existing functionality.

**Comment by vishalmishraa** [comment]
> @hkirat hey I think we should use the chessboardjsx library. I think it can be easily integrated with chess.js as well.
> Using just chess.js might cause problems in the future when adding more and more things
> 
> Happy to integrate it with existing codebase
> 

Yup , chessboardjsx can be easily integrated with chessjs ,

**Comment by vishalmishraa** [comment]
## UPDATE 

### ADDED BOT AVATAR

Screenshot 2024-04-24 at 2 54 16 PM

**Comment by vishalmishraa** [comment]
hi @hkirat  , please check this. , Now this chess Bot is almost similar to chess.com ,  and regarding chessboardjsx library 
as [nimit](https://github.com/code100x/chess/pull/199#issuecomment-2070974475) said , it would be better to use chessboardjsx for future needs too.

**Comment by nimit9** [comment]
The only downside to using chessboardjsx is that a lot of things would be abstracted on the frontend then, thereby giving us less chance to work on the core things of chess.

**Comment by janareddyc7** [comment]
i tried it the pieces are bit laggy with delay can we fix it

**Comment by vishalmishraa** [comment]
> i tried it the pieces are bit laggy with delay can we fix it

Yup , i too want to do more enhancement , I'm just waiting for harkirat.

**Comment by vishalmishraa** [comment]
> i tried it the pieces are bit laggy with delay can we fix it

ok , i checked it again , it is not lagging for me, when i was recording that  video my system was lagging , thats why in video it seems like pieces are laggy .  and i'm waiting for harkirat to come online to know what to do . i too want to do more enchantment .

**Pull request closed without merging**
