### PR TITLE
Feat/postgres prisma

### PR DESCRIPTION
**Pull request by nimit9**
Todo:

- Frontend for joining game
- updating game status in db
- code refactoring

### CODE REVIEW

**Comment by hkirat** [comment]
There's another one from @TanmayDhobale that might conflict here
I've merged that, can u bring this up to date with main?

**Comment by nimit9** [comment]
@hkirat , to update the code according to schema which @TanmayDhobale has suggested will take a lot of time, as it will require deep dive into chess.js Library, he has put it outside the backend folder which shouldn't cause merge conflicts for now, 

We can integrate the schema incrementally. 

Works?

**Comment by TanmayDhobale** [comment]
@nimit9 dude are working on this  #11 or should i work on this ?

**Comment by nimit9** [comment]
This PR is related to #11

**Comment by TanmayDhobale** [comment]
> This PR is related to #11

okay cool. ill pick another one then if ur working

**Comment by nimit9** [comment]
Yep

**Comment by hkirat** [comment]
This was marked as drafts?
Is it good to merge @nimit9 ?

**Comment by nimit9** [comment]
Yeah, good to merge, have mentioned the todos, can be done after this. Will pick them up.

**Pull request merged**
