### PR TITLE
bug:centered arrow

### PR DESCRIPTION
**Pull request by mohitejaikumar**
Arrow was not positioned center to the piece also not responsive .

# Before
Screenshot 2024-04-27 032744
# After
Screenshot 2024-04-27 032835

### CODE REVIEW

**Comment by Sama-004** [comment]
@nimit9

**Comment by nimit9** [comment]
This will be fixed in #223

**Comment by mohitejaikumar** [comment]
Hi @nimit9 , I am new to github , can you explain this.

**Comment by nimit9** [comment]
I'v already raised a PR, which fixes the issue. This is a duplicate PR you've raised. You can close this.

**Comment by mohitejaikumar** [comment]
Ohk , sorry 😞

**Pull request closed without merging**
