### PR TITLE
feat: created distributed game rooms for player with black, white and audience as role

### PR DESCRIPTION
**Pull request by shawakash**
- [x] created distributed game rooms for player with black, white and audience as role using pub sub
- [x] redis running locally
- [x] handle some edge cases for user roles
- [x] initializing game and storing the moves lan in redis queues
- [x] dockerizing the ws app
- [x] added a graphql postgres db using hasura and graphql-zeus for types 
- [x] added api server for user to create an acount
- [x] adds common package for validations constants etc
- [x] adds a worker to process tasks using redis queues
- [ ] verifies the email by a worker
- [x] caches the client metadata
- [x] /user/me endpoint to validate user after a specific time

### CODE REVIEW

**Comment by shawakash** [comment]
@hkirat  ?

**Comment by hkirat** [comment]
bruh
Will review tomorrow

**Comment by shawakash** [comment]
@hkirat  There is no tomorrow 😂

**Comment by hkirat** [comment]
Thanks for the PR
looks very comprehensive
Any reason u chose hasura over prisma + postgres?

**Comment by shawakash** [comment]
> Thanks for the PR looks very comprehensive Any reason u chose hasura over prisma + postgres?

scaling the database and also been more familiar with hasura

**Comment by shawakash** [comment]
@hkirat  any thoughts on distributing the socket server?

**Pull request closed without merging**
