### PR TITLE
Added avatar with logout option

### PR DESCRIPTION
**Pull request by khAja13**
Fixes: #155

Fetching image from only google provider. Not for other providers.

### CODE REVIEW

**Comment by Sama-004** [comment]
@khAja13 Please add screenshots and videos

**Comment by khAja13** [comment]
After logging in using Google provider, you will see a navbar with logo and profile picture

**Comment by khAja13** [comment]
Clicking on logout makes redirection to the home page, but I was not able to remove the cookies. I might take a help in here.

**Comment by hkirat** [comment]
We have it in the sidebar, not needed in the topbar for now

**Pull request closed without merging**
