### PR TITLE
Update ReadMe with execution instructions

### LINKED ISSUE #164: Add setup instructions to the README file

### PR DESCRIPTION
**Pull request by KelvinPuyam**
This PR closes #164 
Changes made:
* [x] Added installation instructions to the README to guide users on setting up the project locally.
* [x] Included usage instructions to start the servers and access the Chess Platform.

### CODE REVIEW

**Comment by Sama-004** [comment]
@KelvinPuyam  Backend setup instructions not provided

**Comment by KelvinPuyam** [comment]
@Sama-004 Backend setup instructions added. Let me know if I should make any changes.

**Comment by hkirat** [comment]
merge conflicts

**Comment by hkirat** [comment]
going to close this, lets create a docker-compose and just use that

**Pull request closed without merging**
