### PR TITLE
Integrate Husky, ESLint, and Prettier with Pre-Commit Hooks

### PR DESCRIPTION
**Pull request by TanmayDhobale**
fixed  issue : #133 

This pull request integrates Husky, ESLint, and Prettier into project setup to enhance code quality , Here are the key changes:

- **Husky**: Configured to manage pre-commit hooks that ensure code quality checks are passed before commits are made.
- **ESLint**: Set up to enforce coding standards and catch JavaScript/TypeScript issues early.
- **Prettier**: Implemented to automatically format code to maintain a consistent style.
- **Pre-Commit Hooks**: Added hooks to run ESLint and Prettier checks on staged files before committing, ensuring only well-formatted and error-free code is committed to the repository.

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by TanmayDhobale** [comment]
Screenshot 2567-04-21 at 2 58 32 AM

**Comment by hkirat** [comment]
lots of conflicts
Can u just add the lint changes . I'll do a wholesale lint on the project

**Comment by TanmayDhobale** [comment]
> lots of conflicts
> Can u just add the lint changes . I'll do a wholesale lint on the project
Sure

**Comment by TanmayDhobale** [comment]
@hkirat now?

**Comment by TanmayDhobale** [comment]
@hkirat  can u check this out

**Comment by TanmayDhobale** [comment]
@siinghd have a look brother

**Comment by TanmayDhobale** [comment]
@hkirat any bounty for this ? 😅🫢

**Pull request merged**
