### PR TITLE
feat: created landing page, auth and user roles.

### PR DESCRIPTION
**Pull request by Neon-20**
**PR adds:**

1. Landing Page ✅
2. Auth using NextAuth ✅ (v5)
3. Active Roles in schema, ADMIN and USER.

@hkirat, once checkout.

https://github.com/code100x/chess/assets/55043383/e29f4192-77c0-4795-bab7-99cfd746c984

### CODE REVIEW

**Comment by darshanCommits** [comment]
I think you should split this PR into multiple different PRs.
It is doing a lot of things and is hard to review because of that.

**Comment by Neon-20** [comment]
Hey, @darshanCommits thanks for the feedback. I could break it down, although it is a newer project, so there are very less chances of merge conflicts. The code is pretty standard, so I dont feel there is a need to do that.

**Comment by hkirat** [comment]
looks like this uses next
I'm doing a merge on master soon with react
Mind updating the changes there?

**Comment by Neon-20** [comment]
Sure can change over there @hkirat .

**Pull request closed without merging**
