### PR TITLE
fixed github login

### LINKED ISSUE #267: Github still seems bonked
This is what I see
Screenshot 2024-04-30 at 12 15 24 PM

### PR DESCRIPTION
**Pull request by Srijan-t0d0**
closes #267

### CODE REVIEW

**Comment by Srijan-t0d0** [comment]
> /bounty $10

@nimit9 @hkirat  how do I claim it?

**Comment by nimit9** [comment]
@Srijan-t0d0 check the announcements channel on discord

**Comment by Srijan-t0d0** [comment]
> @Srijan-t0d0 check the announcements channel on discord

discord link?

**Comment by nimit9** [comment]
> > @Srijan-t0d0 check the announcements channel on discord
> 
> discord link?
> 

Not from the cohort?

**Comment by Srijan-t0d0** [comment]
> > > @Srijan-t0d0 check the announcements channel on discord
> > 
> > 
> > discord link?
> 
> Not from the cohort?

came from youtube stream

**Pull request merged**
