### PR TITLE
fixed public error

### PR DESCRIPTION
**Pull request by nischal-shetty2**
fixes: #246 

added public path in tsconfig.json which fixes the error and changed the paths which gave the error

### CODE REVIEW

**Comment by nimit9** [comment]
@nischal-shetty2 No need for this, can just do `const moveAudio = new Audio('/move.wav');` and this works

**Comment by nischal-shetty2** [comment]
> @nischal-shetty2 No need for this, can just do `const moveAudio = new Audio('/move.wav');` and this works

That neither looks pretty not is it a better alternate. just one config path can solve it, unless there are any set backs doing it this way I don't see a problem

**Comment by nimit9** [comment]
Hey @nischal-shetty2 Yeah correct, importing it and using it is better than creating a url for it, my bad, I thought otherwise

**Pull request merged**
