### PR TITLE
Improves Landing Page UI

### PR DESCRIPTION
**Pull request by adi790uu**
This PR improves the UI of PlayCard component in Landing Page.

issue - #281 

initial UI - 

Screenshot 2024-05-01 at 3 15 25 PM

final UI - 

Screenshot 2024-05-01 at 3 15 40 PM

### CODE REVIEW

**Comment by nimit9** [comment]
Please remove package-lock and yarn-lock changes, and please use yarn to run the project locally.

**Comment by adi790uu** [comment]
@nimit9 is there any specific reason I should use yarn?

**Comment by nimit9** [comment]
Yes we're using yarn for this project. That will ensure consistency

**Comment by adi790uu** [comment]
@nimit9 okay will work on this changes.

**Comment by nimit9** [comment]
@adi790uu, you need to remove the package-lock from root folder, it was present in the apps when monorepofying the app, it needs to be replaced with yarn-lock from all the apps and packages in a separate PR I guess when PR count is ~0.
cc @hkirat

**Comment by adi790uu** [comment]
is this fine @nimit9

**Comment by nimit9** [comment]
Add back the package-lock.json from main in each folders. We'll migrate it to yarn-lock in a separate PR

**Comment by adi790uu** [comment]
@nimit9 its not possible to merge the package-lock.json files from main but i can run npm install in each folder to get the files will it be the right approach

**Comment by nimit9** [comment]
Just copy paste from main, don't need to pull

**Comment by adi790uu** [comment]
@nimit9 I hope this is fine now.

**Comment by nimit9** [comment]
Dont have to delete yarn.lock from root, copy that over as well.

**Comment by adi790uu** [comment]
@nimit9 done

**Comment by nimit9** [comment]
There shouldn't be any diff for yarn.lock, need to paste the latest change for yarn.lock from main

**Comment by adi790uu** [comment]
@nimit9 conflict still exists.

**Comment by nimit9** [comment]
You'll have to resolve the conflicts. It's because other PRs were merged. They might have caused the conflicts.


Yarn lock is still showing diff, just copy from the yarn.lock from latest code, in main branch

**Comment by adi790uu** [comment]
@nimit9 this is fine now.

**Comment by nimit9** [comment]
Still showing lock file changes!

**Comment by adi790uu** [comment]
@nimit9 how is it possible I have copy pasted the yarn.lock file from main branch.

**Comment by nimit9** [comment]
Yeah it's updated now!

**Comment by adi790uu** [comment]
finally :)

**Pull request merged**
