### PR TITLE
Chess UI similart to Chess.com

### LINKED ISSUE #13: Make UI similar to a famous chess website

### PR DESCRIPTION
**Pull request by vishrudh-raj-rs-14**
Closes #13 
Made Chess UI similar to Chess.com
Rebased and removed merge conflicts as told

Screenshot 2024-04-18 at 11 28 27 PM

Also part of cohort(0-100)

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Add some screenrecorded video so that it will be easy for review

**Comment by vishrudh-raj-rs-14** [comment]
Added images in description

**Comment by nimit9** [comment]
Hey, please remove the old folders.

**Comment by hkirat** [comment]
Closing since @nimit9 re-wrote most of this in canvas

**Comment by nimit9** [comment]
Just used canvas for drawing the arrows @hkirat

**Pull request closed without merging**
