### PR TITLE
Feat: added dot in the legal move, showing Turns and rotated the board for diff Colors

### PR DESCRIPTION
**Pull request by Airbornharsh**
added dot from the react-icons package and shortened the get legal moves logic

#68

### CODE REVIEW

**Comment by hkirat** [comment]
please always add screenshots for UI changes

**Comment by Airbornharsh** [comment]
Screenshot from 2024-04-20 08-29-10
Screenshot from 2024-04-20 08-29-17

**Comment by Airbornharsh** [comment]
> please always add screenshots for UI changes

Solves #102 
Rotated the Board and Showing Turns

For White Player
Screenshot from 2024-04-20 08-29-10
For Black Player
Screenshot from 2024-04-20 08-29-17

**Comment by nimit9** [comment]
Hey this is the incorrect way of flipping the board for black, the letters go from h to a, left to right. Have fixed this in #97

**Comment by Airbornharsh** [comment]
Updated the Flipping Logic
@hkirat you can check

https://github.com/code100x/chess/assets/95279849/de7ecedd-6b7b-4487-bbf7-1cf8bab0b8aa

**Comment by hkirat** [comment]
I think https://github.com/code100x/chess/pull/98 closes this

**Pull request closed without merging**
