### PR TITLE
Changed Frontend, Added Reusable Components, Added ShadCn

### PR DESCRIPTION
**Pull request by skushagra9**
image

image

image

image

I know I have currently added shadcn to frontend only, and not in the packages, as there is currently a problem with turborepo. I have figured out a way and it works with tsup. Let me know if you want me to do that way
Current changes are for landing page

### CODE REVIEW

**Comment by nimit9** [comment]
Always a good idea to add screenshots/recording in case of frontend changes

**Comment by skushagra9** [comment]
> Always a good idea to add screenshots/recording in case of frontend changes

its there

**Comment by skushagra9** [comment]
Thanks @hkirat

**Pull request merged**
