### PR TITLE
Improved Chessboard UI, Added env variables, some ts changes and code fixes 

### PR DESCRIPTION
**Pull request by nimit9**
- Added Logic for flipping the board if it's black
- Some ts fixes
- Added .env variables

Made the UI like chess.com, added logic for flipping the board when black, showing valid moves logic

[Screencast from 2024-04-20 06-14-23.webm](https://github.com/code100x/chess/assets/37402791/cfcf31b0-4397-4b81-bb84-12acad6a5552)

Added Latest Move Highlighting:

[Screencast from 2024-04-20 14-50-10.webm](https://github.com/code100x/chess/assets/37402791/e9542b59-ecc1-49ab-bf94-21518f95dfec)

Added highlighting squares and drawing arrows
   p.s - Knight Arrows is pending
   
[Screencast from 2024-04-20 18-39-41.webm](https://github.com/code100x/chess/assets/37402791/5166cee3-b34b-40a4-8bb6-2251ed515c9c)

### CODE REVIEW

**Comment by nimit9** [comment]
Have fixed the red bg color when a piece is selected, and also the dot's color which shows valid moves @hkirat

**Comment by nimit9** [comment]
I think this is readty for review now @hkirat

**Comment by hkirat** [comment]
Any reason for using canvas vs plain div elements?

**Comment by nimit9** [comment]
Using canvas for the arrows.

**Comment by hkirat** [comment]
Thankyou sir, amazing as always

**Comment by nimit9** [comment]
Thank you so much ❤️

**Comment by sanjeevs9** [comment]
Hey nimit how much time u have put for these changes ?

**Pull request merged**
