### PR TITLE
Feat/added themes

### PR DESCRIPTION
**Pull request by manish591**
#### Changes
1. Themes added
2. Loader design updated
3. Ui changes in landing page

#### Images / Video

https://github.com/code100x/chess/assets/79859472/f85bfa3f-3257-4b4d-9461-a842c2cd3407

### CODE REVIEW

**Comment by manish591** [comment]
@hkirat Please review.

**Comment by siinghd** [comment]
Looks fine sirrr, can we add more themes and improve the bubblegum?

**Comment by manish591** [comment]
> Looks fine sirrr, can we add more themes and improve the bubblegum?

Will add more, Will fix the contrast and other problems with the existing themes soon

**Comment by nimit9** [comment]
Hey @siinghd, can we push for the react-chessboard PR, with that things related to theming, etc will become easy

**Pull request merged**
