### PR TITLE
Added Resign Button

### PR DESCRIPTION
**Pull request by nischal-shetty2**
You can now resign a game.
it first asks you if you're sure you want to resign and if yes then it takes you to the home page

https://github.com/code100x/chess/assets/136328410/c41e7299-8b55-404d-a368-ca023419aad6

### CODE REVIEW

**Comment by nimit9** [comment]
This can't be just frontend, it needs to be saved to the db.

I think @devsargam has already raised a PR which solves this.

**Comment by devsargam** [comment]
Yep, #180 solves this

**Comment by hkirat** [comment]
closing in favor of https://github.com/code100x/chess/pull/180

**Comment by nischal-shetty2** [comment]
> Yep, #180 solves this

oh it was hidden between few other commits so i didnt notice it

**Pull request closed without merging**
